name: Build Vue.js 3 Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout do repositório
      uses: actions/checkout@v3

    - name: 🟢 Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: 📦 Instalar dependências
      run: npm install

    - name: 🛠️ Fazer build
      run: npm run build
